export const LANGUAGE_TEXT :any = {
  de: {
    languageLabel: "Sprache",
    languageOptions: { de: "Deutsch", en: "Englisch" },
    header: {
      back: "Zurück zum Invoice Hub",
      title: "Rechnungsprüfung",
      config: "🗂️ Konfiguration",
      tolerance: "⚙️ Toleranzen",
      export: "📤 Exportieren",
    },
    detail: {
      back: "Zurück zur Übersicht",
      invoice: "Rechnung",
      project: "Projekt",
      statusTitle: "Status der Rechnung",
      errorNotice:
        "Die Spedition wurde automatisch über die Abweichung informiert. Sobald eine Stellungnahme vorliegt, kannst du sie hier einsehen. (Demo: Stellungnahme selbst hinterlegen)",
      errorButton: "Stellungnahme erfassen (Demo)",
      responseTitle: "Stellungnahme der Spedition",
      responseSubtitle: "Die Spedition hat geantwortet. Bitte prüfen und ggf. akzeptieren.",
      responseButton: "Stellungnahme anzeigen",
      columns: {
        sendung: "Sendungs-ID",
        carrier: "Spedition",
        surcharges: "Nebenkosten",
        orderSum: "Auftrags Summe (€)",
        invoiceSum: "Rechnungs Summe (€)",
        difference: "Differenz",
        status: "Status",
      },
      surchargeTable: {
        title: "Nebenkosten – Detailansicht",
        label: "Bezeichnung",
        orderSum: "Auftrags Summe (€)",
        invoiceSum: "Rechnungs Summe (€)",
        difference: "Differenz",
        status: "Status",
      },
    },
    overview: {
      columns: {
        invoiceNumber: "Rechnungsnummer",
        invoiceDate: "Rechnungsdatum",
        carrier: "Spedition",
        orderSum: "Auftrags Summe",
        invoiceSum: "Rechnungs Summe",
        difference: "Differenz",
        status: "Status",
      },
      filters: {
        carrier: "Spedition",
        invoiceNumber: "Rechnungsnummer",
        fromDate: "Von (Datum)",
        toDate: "Bis (Datum)",
        clear: "Zeitraum löschen",
        all: "Alle",
      },
    },
    config: {
      dialogTitle: "Auftrags- & Tarifsteuerung",
      pricing: {
        intro:
          "Pflege mehrere Speditionen auf Basis desselben Auftragsdaten-Eingangs. Je Spedition gibt es Frachtberechnung, Tarife und Nebenkosten.",
        sharedInputNote:
          "Der Auftragsdaten-Eingang bleibt für alle gleich – hier pflegst du nur die Preismodelle pro Spedition.",
        chipsHelp: "Klicke eine Spedition an, um ihre Eingaben zu bearbeiten.",
        addCarrier: "Spedition hinzufügen",
        newCarrierPlaceholder: "Name der Spedition",
        currentCarrierLabel: "Aktive Spedition",
        addCarrierDialog: {
          title: "Spedition anlegen",
          priceFixTitle: "Speditionspreis anlegen",
          name: "Firmenname",
          street: "Straße",
          houseNumber: "Hausnummer",
          zip: "Postleitzahl",
          city: "Ort",
          country: "Land",
          contact: "Ansprechpartner",
          phone: "Telefonnummer",
          email: "E-Mail",
          customerNumber: "Kundennummer",
          save: "Anlegen",
          cancel: "Abbrechen",
        },
        carrierLabel: "Speditionen",
        empty: "Noch keine Spedition angelegt.",
        freight: {
          title: "Frachtberechnung",
          countryTitle: "Länderübersicht (Demo)",
          countryAddLabel: "Land hinzufügen",
          countryPlaceholder: "Land auswählen",
          calculationTitle: "Berechnungsart",
          calculationModes: {
            cbm: "Kubikmeter werden berücksichtigt",
            ldm: "Lademeter werden berücksichtigt",
            weight: "Berechnung nach Effektivgewicht",
          },
          consolidated: "Konsolidierte Abrechnung (Sendungszusammenfassung)",
          bulkyTitle: "Sperrigkeiten",
          bulkyCbm: "Kubikmeter",
          bulkyLdm: "Lademeter",
          advancedTitle: "Erweiterte Optionen",
          ldmFromKg: "Lademeterberechnung ab Kg",
          ldmFromLdm: "Lademeterberechnung ab Lademeter",
          minWeightTitle: "Minimalgewicht je Verpackungsart",
          minWeightHeaders: {
            code: "Kürzel",
            internalCode: "Internes Kürzel",
            description: "Beschreibung",
            internalDescription: "Interne Beschreibung",
            weight: "Gewicht in Kg",
          },
          customMinWeightTitle: "Zusatz Minimalgewicht je Verpackungsart",
          addCustomRow: "Zusätzliche Zeile hinzufügen",
          deleteRow: "Zeile löschen",
          import: "Importieren",
          export: "Exportieren",
          customEmpty: "Keine zusätzlichen Minimalgewichte erfasst.",
        },
        tariffs: {
          title: "Tarife",
          countryTitle: "Länderübersicht (Demo)",
          countryAddLabel: "Land hinzufügen",
          countryPlaceholder: "Land auswählen",
          tariffTypeLabel: "Tarif Art",
          tariffTypes: [
            "Gewicht",
            "Paletten",
            "Paket (Colli)",
            "Lademeter",
            "Kilometer",
            "Kilogrammsatz",
            "Gewicht-100-kg-Satz",
            "Gewicht-100-kg-Satz (aufgerundet auf volle 100)",
            "Gewicht-100-kg-Satz (aufgerundet auf volle 10)",
          ],
          addZone: "Zone hinzufügen",
          zoneName: "Zonenname",
          zoneZips: "PLZ / Relation",
          zoneMin: "Min",
          zoneMax: "Max",
          weightHeader: "Gewicht",
          valuePlaceholder: "Preis",
          columns: {
            tier: "Staffel / Relation",
            price: "Preis",
            validFrom: "Gültig ab",
            validTo: "Gültig bis",
            currency: "Währung",
          },
          addRow: "Tarifzeile hinzufügen",
          importCsv: "Import CSV",
          exportCsv: "Export als CSV",
          helper: "Staffeln kannst du später aus dem Backend füllen.",
        },
        surcharges: {
          title: "Nebenkosten",
          countryTitle: "Länderübersicht (Demo)",
          countryAddLabel: "Land hinzufügen",
          countryPlaceholder: "Land auswählen",
          columns: {
            label: "Bezeichnung",
            type: "Art",
            amount: "Wert",
            unit: "Einheit",
            description: "Beschreibung",
          },
          types: { percent: "% vom Frachtpreis", flat: "Fixbetrag" },
          addRow: "Nebenkosten hinzufügen",
          importCsv: "Import CSV",
          exportCsv: "Export als CSV",
          valuePlaceholder: "Betrag",
        },
        actions: {
          removeCarrier: "Spedition entfernen",
        },
        defaults: {
          freight: {
            calculationMode: "cbm",
            consolidatedBilling: false,
            bulkyCbm: "",
            bulkyLdm: "",
            ldmFromKg: "",
            ldmFromLdm: "",
          },
          tariff: {
            tariffType: "100-kg rate (rounded to 100)",
            zones: [
              { name: "Zone 1", zips: "20-22", min: "", max: "" },
              { name: "Zone 2", zips: "23", min: "", max: "" },
            ],
            rows: ["100", "200", "300", "400", "500", "600"],
          },
          surcharges: {
            rows: [
              { label: "Maut", amount: "0,00", unit: "%", description: "Fester Zuschlag in Euro / Prozentualer Zuschlag" },
              { label: "Dieselzuschlag", amount: "0,00", unit: "%", description: "Prozentualer Zuschlag / floatenmodell" },
              { label: "Express Next Day", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Express 12:00 Uhr", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Express 10:00 Uhr", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Express 08:00 Uhr", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Brennerzuschlag", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Fixtermin", amount: "9,50", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "E-Mail Avis", amount: "3,50", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Telefonisches Avis", amount: "7,50", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Booking in Avis", amount: "3,50", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Gefahrgutzuschlag", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Langzuschlag", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Kurzwochenzuschlag", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Palettentausch", amount: "0,00", unit: "€", description: "Feste Gebühr je Palette in Euro" },
              { label: "Gitterboxtausch", amount: "0,00", unit: "€", description: "Feste Gebühr je Gitterbox in Euro" },
              { label: "Spediteurbescheinigung", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "B2C Zuschlag (national)", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "B2C Zuschlag (international)", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Security Fee", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Versicherung", amount: "0,00", unit: "€", description: "Prämie nach Warenwert daher kann auch ein Text eingegeben werden" },
              { label: "Porto/Papiere", amount: "0,00", unit: "€", description: "Fester Zuschlag je Rechnung in Euro" },
              { label: "Eigene 1", amount: "0,00", unit: "€", description: "Beschreibung eingeben" },
              { label: "Eigene 2", amount: "0,00", unit: "€", description: "Beschreibung eingeben" },
              { label: "Eigene 3", amount: "0,00", unit: "€", description: "Beschreibung eingeben" },
              { label: "Eigene 4", amount: "0,00", unit: "€", description: "Beschreibung eingeben" },
              { label: "Eigene 5", amount: "0,00", unit: "€", description: "Beschreibung eingeben" },
            ],
          },
          newCarrierName: "Neue Spedition",
        },
      },
    },
    dialogs: {
      responseInputTitle: "Stellungnahme erfassen (Demo)",
      responseInputDescription:
        "Hier kannst du zu Demonstrationszwecken eine Antwort der Spedition hinterlegen. In der echten Anwendung würde diese Nachricht automatisch eingehen.",
      responsePlaceholder: "Erläuterung der Spedition…",
      cancel: "Abbrechen",
      save: "Speichern",
      responseViewerTitle: "Stellungnahme der Spedition",
      responseViewerNoData: "Keine Stellungnahme vorhanden.",
      responseViewerHint:
        "Bei Unklarheiten oder Meinungsverschiedenheiten bitte den Spediteur telefonisch kontaktieren.",
      clarificationTitle: "Klärungsverlauf",
      clarificationEmpty: "Noch keine Klärungen erfasst.",
      clarificationPlaceholder: "Bitte erläuternde Rückfrage oder Kommentar eingeben …",
      clarificationSubmit: "Kommentar hinzufügen",
      clarificationFromShipper: "Versender",
      clarificationFromCarrier: "Spediteur",
      clarificationDemoShipper:
        "Die Position 4711 ist laut unserer Kalkulation zu hoch. Könnt ihr bitte noch einmal die vereinbarte Staffel prüfen?",
      clarificationDemoCarrier:
        "Wir prüfen das Thema intern und melden uns mit einer korrigierten Rechnung bis morgen.",
      receivedAt: "Eingegangen am:",
      acceptInvoice: "Abrechnung akzeptieren",
      toleranceTitle: "Toleranzgrenzen definieren",
      toleranceFreight: "Frachtkosten (Auftrags vs. Rechnungs Summe) [%]",
      toleranceDefaultSurcharge: "Standard Nebenkosten [%]",
      specificSurcharges: "Spezifische Nebenkosten-Toleranzen",
      noOverrides: "Noch keine individuellen Toleranzen definiert.",
      addOverride: "Nebenkosten-Toleranz hinzufügen",
      overrideLabel: "Bezeichnung",
      overridePercent: "Toleranz (%)",
      close: "Schließen",
      responseDialogClose: "Schließen",
      importDialogTitle: "Sendungsdaten ersetzen?",
      importDialogDescription:
        'Die Datei "{fileName}" wurde erkannt.\nSollen die bestehenden Sendungsdaten ersetzt werden?',
      onlyNegativeLabel: "Nur Abweichungen mit negativer Differenz berücksichtigen",
      correctionTitle: "Korrigierte Unterlagen (Demo)",
      correctionInvoiceLabel: "Neue Rechnungsnummer",
      correctionStornoLabel: "Storno-Rechnung",
      correctionCreditLabel: "Gutschrift",
      correctionInfo:
        "Die Spedition lädt eine korrigierte PDF hoch und stellt Storno/Gutschrift bereit. Diese Felder simulieren den Prozess.",
    },
    buttons: {
      export: "📤 Exportieren",
      tolerance: "⚙️ Toleranzen",
      exportPlain: "Exportieren",
    },
    status: {
      accepted: "Akzeptiert",
      ok: "Alles okay",
      error: "Fehlerhafte Abrechnung",
      noData: "Keine Daten",
    },
    nebPreview: {
      title: "Länderübersicht (Demo)",
      addPlaceholder: "Weiteres Land hinzufügen (Demo)",
      addLabel: "Land hinzufügen:",
      noCountries: "Noch keine Länder verfügbar.",
      export: "Export CSV",
      import: "Import CSV",
      info: "Sobald dein Backend angebunden ist, landen hier die echten Nebenkosten-Tabellen inkl. Export, Import und Pflege-Workflows.",
      columns: {
        cost: "Kostenblock",
        description: "Beschreibung",
        unit: "Einheit",
        value: "Wert",
        updated: "Letzte Änderung",
      },
    },
    shipments: {
      summary: {
        active: "Aktive Datensätze",
        lastUpdate: "Letzte Aktualisierung",
        importSource: "Importquelle",
        importValue: "CSV Upload",
        lastUpdateValue: "12.02.2025 – 09:42 Uhr",
      },
      buttons: {
        add: "Sendung hinzufügen",
        import: "Import CSV",
        export: "Export als CSV",
        clear: "Sendedaten leeren",
      },
      table: {
        shipmentId: "Sendungs-ID",
        shipDate: "Versanddatum",
        zipFrom: "PLZ Versand",
        zipTo: "PLZ Empfang",
        city: "Ort",
        country: "Land",
        packaging: "Verpackungsart",
        weight: "Effektives Gewicht",
        loadingMeters: "Lademeter",
        express: "Express Next Day",
        b2c: "B2C Zuschlag (national)",
      },
      info:
        "Diese Vorschau spiegelt den späteren „Auftragsdaten-Eingang“ wider – inklusive CSV-Import, manueller Erfassung und Fortschrittsanzeige. Sobald dein Backend (Projekt- & Sendungsdaten) angeschlossen ist, ersetzt du diese Demo durch die ShipmentData-Logik.",
      note:
        "Inline-Editing (MUI DataGrid), CSV-Export via Toolbar, Duplikatschutz für Express/B2C-Flags und Validierungen (z. B. PLZ, Verpackungstypen) laufen in der echten ShipmentDataTable. Bis die API greift, dient diese Kachel als visuelle Referenz.",
    },
    common: {
      noContent: "Keine Inhalte verfügbar.",
      delete: "Löschen",
      booleanYes: "Ja",
      booleanNo: "Nein",
    },
    carrierView: {
      button: "Spediteur-Ansicht (Demo)",
      title: "Spediteur-Portal (Demo)",
      intro:
        "So sieht die Oberfläche für Speditionen aus, sobald ihr eine Rechnung mit Abweichungen zur Klärung verschickt.",
      summaryTitle: "Rechnungsübersicht",
      summary: {
        invoice: "Rechnung",
        project: "Projekt",
        orderTotal: "Auftrags Summe",
        invoiceTotal: "Rechnungs Summe",
        difference: "Differenz",
      },
      tableTitle: "Auffällige Positionen",
      columns: {
        item: "Position",
        type: "Art",
        expected: "Erwartet",
        actual: "Abgerechnet",
        difference: "Differenz",
      },
      freightType: "Fracht",
      surchargeType: "Nebenkosten",
      shipmentLabel: "Sendung",
      noDiscrepancies: "Keine Abweichungen gefunden.",
      responseTitle: "Stellungnahme senden",
      responsePlaceholder: "Bitte erläutere kurz, wie sich die Abweichung erklärt …",
      submit: "Antwort senden",
      info: "Diese Demo simuliert den Link, den Speditionen nach einer abgelehnten Rechnung per E-Mail erhalten würden.",
    },
    countries: {
      DE: "Deutschland",
      INT: "International",
      FR: "Frankreich",
      PL: "Polen",
      ES: "Spanien",
    },
    surcharges: {
      deTitle: "Deutschland (DE)",
      deNote: "Basis: Projekt Hamburg AB – Stand Woche 37/2024",
      intTitle: "International (INT)",
      intNote: "Placeholder für zusätzliche Länder bzw. Regionen",
      dieselFloater: "Diesel Floater",
      dieselDescription: "Automatische Anpassung an BAFA-Index",
      toll: "Maut",
      tollDescription: "Fix gemäß Auftrag",
      pickup: "Pickup-Pauschale",
      pickupDescription: "Pro Pickup & Tag",
      handling: "Handling Fee",
      handlingDescription: "Terminal Handling",
      customs: "Zollabfertigung",
      customsDescription: "Fixe Pauschale",
      example: "Beispielposition",
      exampleDescription: "Sobald Daten vorhanden sind, erscheint hier die Detail-Logik.",
      unitPercent: "% vom Frachtpreis",
      unitEuroPerKm: "€ / km",
      unitEuro: "€",
      unitEuroPerShipment: "€ pro Sendung",
      unitDash: "—",
      updated: "Letzte Änderung",
      defaultNote: "Noch keine Nebenkosten gepflegt. Hier kannst du später individuelle Zuschläge hinterlegen.",
    },
    configSections: {
      pricing: {
        title: "Speditionen (Preise)",
        description:
          "Pflege Frachtberechnung, Tarife und Nebenkosten je Spedition mit identischem Auftragsdaten-Eingang.",
        actionLabel: "Preismodell pflegen",
      },
      auftragsdaten: {
        title: "Auftragsdaten-Eingang",
        description:
          "Hier laufen zukünftig alle Aufträge und Sendungen ein. Bis der Produktivcode steht, zeigen wir Platzhalter.",
        placeholders: [
          { label: "Importquelle", value: "CSV / API (Platzhalter)" },
          { label: "Letzte Aktualisierung", value: "—" },
          { label: "Validierungsstatus", value: "wartet auf Code" },
        ],
        actionLabel: "Import konfigurieren",
        actionHint: "Dieser Button ist deaktiviert, bis du den finalen Code einfügst.",
      },
      reconciliation: {
        title: "Preisabgleich",
        description:
          "Hier prüfst du später, ob das System anhand der importierten Daten alle Preise und Zuschläge gefunden hat.",
        placeholders: [
          { label: "Abgerechnete Sendungen", value: "—" },
          { label: "Fehlende Preise", value: "—" },
          { label: "Letzte Prüfung", value: "—" },
        ],
        actionLabel: "Abgleich starten",
        actionHint: "Sobald deine Prüf-Logik angebunden ist, läuft hier der automatische Preisabgleich.",
      },
    },
  },
  en: {
    languageLabel: "Language",
    languageOptions: { de: "German", en: "English" },
    header: {
      back: "Back to Invoice Hub",
      title: "Invoice Review",
      config: "🗂️ Configuration",
      tolerance: "⚙️ Tolerances",
      export: "📤 Export",
    },
    detail: {
      back: "Back to Overview",
      invoice: "Invoice",
      project: "Project",
      statusTitle: "Invoice Status",
      errorNotice:
        "The carrier was notified automatically. As soon as a statement arrives, you can view it here. (Demo: record the statement yourself)",
      errorButton: "Record Statement (Demo)",
      responseTitle: "Carrier Response",
      responseSubtitle: "The carrier replied. Please review and accept if applicable.",
      responseButton: "View Response",
      columns: {
        sendung: "Shipment ID",
        carrier: "Carrier",
        surcharges: "Surcharges",
        orderSum: "Order Total (€)",
        invoiceSum: "Invoice Total (€)",
        difference: "Difference",
        status: "Status",
      },
      surchargeTable: {
        title: "Surcharge Details",
        label: "Label",
        orderSum: "Order Total (€)",
        invoiceSum: "Invoice Total (€)",
        difference: "Difference",
        status: "Status",
      },
    },
    overview: {
      columns: {
        invoiceNumber: "Invoice Number",
        invoiceDate: "Invoice Date",
        carrier: "Carrier",
        orderSum: "Order Total",
        invoiceSum: "Invoice Total",
        difference: "Difference",
        status: "Status",
      },
      filters: {
        carrier: "Carrier",
        invoiceNumber: "Invoice Number",
        fromDate: "From (date)",
        toDate: "To (date)",
        clear: "Clear range",
        all: "All",
      },
    },
    config: {
      dialogTitle: "Order & Tariff Workspace",
      pricing: {
        intro:
          "Maintain multiple carriers on the same order data intake. Each carrier has freight basis, tariffs, and surcharges.",
        sharedInputNote:
          "The order data intake stays identical for all carriers; only the pricing differs per carrier.",
        chipsHelp: "Select a carrier chip to edit its entries.",
        addCarrier: "Add carrier",
        newCarrierPlaceholder: "Carrier name",
        currentCarrierLabel: "Active carrier",
        addCarrierDialog: {
          title: "Add carrier",
          priceFixTitle: "Set carrier price",
          name: "Company name",
          street: "Street",
          houseNumber: "No.",
          zip: "ZIP",
          city: "City",
          country: "Country",
          contact: "Contact person",
          phone: "Phone",
          email: "E-mail",
          customerNumber: "Customer number",
          save: "Create",
          cancel: "Cancel",
        },
        carrierLabel: "Carriers",
        empty: "No carriers yet.",
        freight: {
          title: "Freight basis",
          countryTitle: "Country overview (demo)",
          countryAddLabel: "Add country",
          countryPlaceholder: "Select country",
          calculationTitle: "Calculation type",
          calculationModes: {
            cbm: "Count cubic meters",
            ldm: "Count loading meters",
            weight: "Use actual weight",
          },
          consolidated: "Consolidated billing (shipment summary)",
          bulkyTitle: "Bulky goods",
          bulkyCbm: "Cubic meters",
          bulkyLdm: "Loading meters",
          advancedTitle: "Advanced options",
          ldmFromKg: "Loading meter calc from kg",
          ldmFromLdm: "Loading meter calc from ldm",
          minWeightTitle: "Minimum weight per packaging",
          minWeightHeaders: {
            code: "Code",
            internalCode: "Internal code",
            description: "Description",
            internalDescription: "Internal description",
            weight: "Weight in kg",
          },
          customMinWeightTitle: "Additional minimum weights",
          addCustomRow: "Add row",
          deleteRow: "Delete row",
          import: "Import",
          export: "Export",
          customEmpty: "No additional minimum weights yet.",
        },
        tariffs: {
          title: "Tariffs",
          countryTitle: "Country overview (demo)",
          countryAddLabel: "Add country",
          countryPlaceholder: "Select country",
          tariffTypeLabel: "Tariff type",
          tariffTypes: [
            "Weight",
            "Pallets",
            "Parcel (colli)",
            "Loading meters",
            "Kilometers",
            "Per-kg rate",
            "100-kg rate",
            "100-kg rate (rounded to 100)",
            "100-kg rate (rounded to 10)",
          ],
          addZone: "Add zone",
          zoneName: "Zone name",
          zoneZips: "ZIPs / relation",
          zoneMin: "Min",
          zoneMax: "Max",
          weightHeader: "Weight",
          valuePlaceholder: "Rate",
          columns: {
            tier: "Tier / relation",
            price: "Price",
            validFrom: "Valid from",
            validTo: "Valid to",
            currency: "Currency",
          },
          addRow: "Add tariff row",
          importCsv: "Import CSV",
          exportCsv: "Export CSV",
          helper: "Later you can hydrate these tiers from the backend.",
        },
        surcharges: {
          title: "Surcharges",
          countryTitle: "Country overview (demo)",
          countryAddLabel: "Add country",
          countryPlaceholder: "Select country",
          columns: {
            label: "Label",
            type: "Type",
            amount: "Amount",
            unit: "Unit",
            description: "Description",
          },
          types: { percent: "% of freight", flat: "Flat fee" },
          addRow: "Add surcharge",
          importCsv: "Import CSV",
          exportCsv: "Export CSV",
          valuePlaceholder: "Value",
        },
        actions: {
          removeCarrier: "Remove carrier",
        },
        defaults: {
          freight: {
            calculationMode: "cbm",
            consolidatedBilling: false,
            bulkyCbm: "",
            bulkyLdm: "",
            ldmFromKg: "",
            ldmFromLdm: "",
          },
          tariff: {
            tariffType: "Gewicht-100-kg-Satz (aufgerundet auf volle 100)",
            zones: [
              { name: "Zone 1", zips: "20-22", min: "", max: "" },
              { name: "Zone 2", zips: "23", min: "", max: "" },
            ],
            rows: ["100", "200", "300", "400", "500", "600"],
          },
          surcharges: {
            rows: [
              { label: "Maut", amount: "0,00", unit: "%", description: "Fester Zuschlag in Euro / Prozentualer Zuschlag" },
              { label: "Dieselzuschlag", amount: "0,00", unit: "%", description: "Prozentualer Zuschlag / floatenmodell" },
              { label: "Express Next Day", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Express 12:00 Uhr", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Express 10:00 Uhr", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Express 08:00 Uhr", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Brennerzuschlag", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Fixtermin", amount: "9,50", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "E-Mail Avis", amount: "3,50", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Telefonisches Avis", amount: "7,50", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Booking in Avis", amount: "3,50", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Gefahrgutzuschlag", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Langzuschlag", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Kurzwochenzuschlag", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Palettentausch", amount: "0,00", unit: "€", description: "Feste Gebühr je Palette in Euro" },
              { label: "Gitterboxtausch", amount: "0,00", unit: "€", description: "Feste Gebühr je Gitterbox in Euro" },
              { label: "Spediteurbescheinigung", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "B2C Zuschlag (national)", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "B2C Zuschlag (international)", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Security Fee", amount: "0,00", unit: "€", description: "Fester Zuschlag je Sendung in Euro" },
              { label: "Versicherung", amount: "0,00", unit: "€", description: "Prämie nach Warenwert daher kann auch ein Text eingegeben werden" },
              { label: "Porto/Papiere", amount: "0,00", unit: "€", description: "Fester Zuschlag je Rechnung in Euro" },
              { label: "Eigene 1", amount: "0,00", unit: "€", description: "Beschreibung eingeben" },
              { label: "Eigene 2", amount: "0,00", unit: "€", description: "Beschreibung eingeben" },
              { label: "Eigene 3", amount: "0,00", unit: "€", description: "Beschreibung eingeben" },
              { label: "Eigene 4", amount: "0,00", unit: "€", description: "Beschreibung eingeben" },
              { label: "Eigene 5", amount: "0,00", unit: "€", description: "Beschreibung eingeben" },
            ],
          },
          newCarrierName: "New carrier",
        },
        presets: {
          carriers: [
            {
              name: "NordCargo",
              freight: {
              },
              tariffs: {
                countryCodes: ["DE"],
                byCountry: {
                  DE: {
                    tariffType: "Weight 100kg band",
                    zones: [
                      { name: "Dachser", zips: "20-22" },
                      { name: "Hellmann", zips: "23" },
                    ],
                    rows: ["100", "200", "300", "400", "500", "600"],
                  },
                },
              },
              surcharges: [
                { label: "Diesel floater", type: "percent", amount: "5.2 %" },
                { label: "Toll", type: "flat", amount: "€0.12 / km" },
                { label: "Notification / delivery", type: "flat", amount: "€18.00" },
              ],
            },
            {
              name: "Rhine Logistics",
              freight: {
              },
              tariffs: {
                countryCodes: ["DE", "INT"],
                byCountry: {
                  DE: {
                    tariffType: "Domestic DE",
                    zones: [
                      { name: "North", zips: "20-29" },
                      { name: "South", zips: "80-89" },
                    ],
                    rows: ["100", "200", "300", "400", "500"],
                  },
                  INT: {
                    tariffType: "BeNeLux",
                    zones: [{ name: "Benelux", zips: "BE/NL/LU" }],
                    rows: ["100", "200", "300", "400", "500"],
                  },
                },
              },
              surcharges: [
                { label: "Handling", type: "flat", amount: "€12.50" },
                { label: "Pick-up", type: "flat", amount: "€25.00" },
              ],
            },
          ],
        },
      },
    },
    dialogs: {
      responseInputTitle: "Capture Statement (Demo)",
      responseInputDescription:
        "Use this area to record a carrier response for demo purposes. In production the message would be received automatically.",
      responsePlaceholder: "Carrier explanation…",
      cancel: "Cancel",
      save: "Save",
      responseViewerTitle: "Carrier Statement",
      responseViewerNoData: "No statement available.",
      responseViewerHint:
        "If anything is unclear, please contact the carrier by phone to clarify the situation.",
      clarificationTitle: "Clarification thread",
      clarificationEmpty: "No clarifications recorded yet.",
      clarificationPlaceholder: "Leave a short follow-up question or comment…",
      clarificationSubmit: "Add comment",
      clarificationFromShipper: "Shipper",
      clarificationFromCarrier: "Carrier",
      clarificationDemoShipper:
        "Line item 4711 still looks too high on our side. Could you double-check the agreed tier?",
      clarificationDemoCarrier:
        "We will review this internally and send an updated invoice by tomorrow.",
      receivedAt: "Received:",
      acceptInvoice: "Accept Invoice",
      toleranceTitle: "Define tolerance levels",
      toleranceFreight: "Freight (Order vs. Invoice Total) [%]",
      toleranceDefaultSurcharge: "Default Surcharge [%]",
      specificSurcharges: "Specific surcharge tolerances",
      noOverrides: "No individual tolerances defined yet.",
      addOverride: "Add surcharge tolerance",
      overrideLabel: "Label",
      overridePercent: "Tolerance (%)",
      close: "Close",
      responseDialogClose: "Close",
      importDialogTitle: "Replace shipment data?",
      importDialogDescription:
        'The file "{fileName}" was detected.\nDo you want to replace the existing shipment data?',
      onlyNegativeLabel: "Only flag deviations where the invoice exceeds the order value",
      correctionTitle: "Corrected documents (demo)",
      correctionInvoiceLabel: "New invoice number",
      correctionStornoLabel: "Storno invoice",
      correctionCreditLabel: "Credit note",
      correctionInfo:
        "Carriers will upload a corrected PDF plus storno/credit references. These placeholders simulate that workflow.",
    },
    buttons: {
      export: "📤 Export",
      tolerance: "⚙️ Tolerances",
      exportPlain: "Export",
    },
    status: {
      accepted: "Accepted",
      ok: "All good",
      error: "Incorrect billing",
      noData: "No data",
    },
    nebPreview: {
      title: "Country overview (demo)",
      addPlaceholder: "Add another country (demo)",
      addLabel: "Add country:",
      noCountries: "No countries available.",
      export: "Export CSV",
      import: "Import CSV",
      info: "Once your backend is connected this area will display the real surcharge tables incl. export, import and maintenance workflows.",
      columns: {
        cost: "Cost block",
        description: "Description",
        unit: "Unit",
        value: "Value",
        updated: "Last update",
      },
    },
    shipments: {
      summary: {
        active: "Active records",
        lastUpdate: "Last update",
        importSource: "Import source",
        importValue: "CSV upload",
        lastUpdateValue: "02/12/2025 – 09:42 AM",
      },
      buttons: {
        add: "Add shipment",
        import: "Import CSV",
        export: "Export CSV",
        clear: "Clear shipments",
      },
      table: {
        shipmentId: "Shipment ID",
        shipDate: "Ship date",
        zipFrom: "Origin ZIP",
        zipTo: "Destination ZIP",
        city: "City",
        country: "Country",
        packaging: "Packaging type",
        weight: "Effective weight",
        loadingMeters: "Loading meters",
        express: "Express next day",
        b2c: "B2C surcharge (domestic)",
      },
      info:
        'This preview represents the upcoming “Order data intake” workspace – incl. CSV import, manual entry, and progress tracking. Once your backend is hooked up, replace this demo with the real ShipmentData logic.',
      note:
        "Inline editing (MUI DataGrid), CSV export toolbar, dedupe logic for Express/B2C flags and validations (e.g. ZIP, packaging) will run in the real ShipmentDataTable. Until then this card serves as a visual placeholder.",
    },
    common: {
      noContent: "No content available.",
      delete: "Delete",
      booleanYes: "Yes",
      booleanNo: "No",
    },
    carrierView: {
      button: "Carrier View (Demo)",
      title: "Carrier Portal (Demo)",
      intro:
        "This is the screen carriers will see when they receive a rejected invoice link for clarification.",
      summaryTitle: "Invoice overview",
      summary: {
        invoice: "Invoice",
        project: "Project",
        orderTotal: "Order total",
        invoiceTotal: "Invoice total",
        difference: "Difference",
      },
      tableTitle: "Flagged positions",
      columns: {
        item: "Position",
        type: "Type",
        expected: "Expected",
        actual: "Invoiced",
        difference: "Difference",
      },
      freightType: "Freight",
      surchargeType: "Surcharge",
      shipmentLabel: "Shipment",
      noDiscrepancies: "No discrepancies detected.",
      responseTitle: "Submit statement",
      responsePlaceholder: "Please explain briefly what caused the deviation…",
      submit: "Send reply",
      info: "This demo mimics the link a carrier would open after receiving an e-mail about a rejected invoice.",
    },
    countries: {
      DE: "Germany",
      INT: "International",
      FR: "France",
      PL: "Poland",
      ES: "Spain",
    },
    surcharges: {
      deTitle: "Germany (DE)",
      deNote: "Basis: Project Hamburg AB – Week 37/2024",
      intTitle: "International (INT)",
      intNote: "Placeholder for additional countries or regions",
      dieselFloater: "Diesel floater",
      dieselDescription: "Automatic adjustment to BAFA index",
      toll: "Toll",
      tollDescription: "Fixed per contract",
      pickup: "Pickup fee",
      pickupDescription: "Per pickup & day",
      handling: "Handling fee",
      handlingDescription: "Terminal handling",
      customs: "Customs clearance",
      customsDescription: "Fixed flat rate",
      example: "Example position",
      exampleDescription: "Once data is available the detail logic will be shown here.",
      unitPercent: "% of freight",
      unitEuroPerKm: "€ / km",
      unitEuro: "€",
      unitEuroPerShipment: "€ per shipment",
      unitDash: "—",
      updated: "Last update",
      defaultNote: "No surcharges recorded yet. You can add customer-specific add-ons here later.",
    },
    configSections: {
      pricing: {
        title: "Carriers (pricing)",
        description:
          "Maintain freight basis, tariffs, and surcharges per carrier while using the same order data intake.",
        actionLabel: "Maintain pricing model",
      },
      auftragsdaten: {
        title: "Order data intake",
        description:
          "All incoming shipments will appear here later. Until the production code lands, we show placeholders only.",
        placeholders: [
          { label: "Import source", value: "CSV / API (placeholder)" },
          { label: "Last update", value: "—" },
          { label: "Validation status", value: "waiting for code" },
        ],
        actionLabel: "Configure import",
        actionHint: "This button stays disabled until you provide the final code.",
      },
      reconciliation: {
        title: "Price check",
        description:
          "This is where you will verify if the system found all prices and surcharges based on the imported data.",
        placeholders: [
          { label: "Settled shipments", value: "—" },
          { label: "Missing prices", value: "—" },
          { label: "Last check", value: "—" },
        ],
        actionLabel: "Run comparison",
        actionHint: "Once your validation logic is ready, the automatic check will run here.",
      },
    },
  },
};

export const BASE_COUNTRY_OPTIONS = [
  { code: "DE", flag: "🇩🇪" },
  { code: "INT", flag: "🌍" },
  { code: "FR", flag: "🇫🇷" },
  { code: "PL", flag: "🇵🇱" },
  { code: "ES", flag: "🇪🇸" },
];


export const MIN_WEIGHT_DEFAULTS = [
  { code: "VP", description: "Viertelpalette", weight: "" },
  { code: "KT", description: "Karton", weight: "" },
  { code: "CC", description: "Collico", weight: "" },
  { code: "HP", description: "Halbpalette", weight: "" },
  { code: "RC", description: "Rollcontainer", weight: "" },
  { code: "CP", description: "Chep-Palette", weight: "" },
  { code: "CT", description: "Container", weight: "" },
  { code: "EB", description: "Einweg-Behälter", weight: "" },
  { code: "EP", description: "Einwegpalette", weight: "" },
  { code: "EW", description: "Einwegpalette", weight: "" },
  { code: "FP", description: "DB Euro-Flachpalette", weight: "150" },
  { code: "GP", description: "Gitterboxpalette", weight: "" },
  { code: "IB", description: "IBC-Behälter", weight: "" },
  { code: "KP", description: "Kundeneigene Palette", weight: "" },
  { code: "PL", description: "Palette", weight: "" },
  { code: "RP", description: "Rahmenpalette", weight: "" },
  { code: "TC", description: "Tankcontainer", weight: "" },
  { code: "VG", description: "Verschlag", weight: "" },
  { code: "XP", description: "Palette", weight: "" },
];

export const SHIPMENT_SAMPLE_ROWS_BASE = [
  {
    shipmentId: "SID-2048",
    date: { de: "12.02.2025", en: "02/12/2025" },
    zipFrom: "20457",
    zipTo: "13353",
    city: "Berlin",
    country: "DE",
    packaging: { de: "FP (Flachpalette)", en: "FP (flat pallet)" },
    weight: { de: "1.250 kg", en: "1,250 kg" },
    loadingMeters: { de: "3,20", en: "3.20" },
    expressNextDay: true,
    b2cNational: false,
  },
  {
    shipmentId: "SID-2047",
    date: { de: "11.02.2025", en: "02/11/2025" },
    zipFrom: "20457",
    zipTo: "80331",
    city: "München",
    country: "DE",
    packaging: { de: "GP (Gitterbox)", en: "GP (cage pallet)" },
    weight: { de: "980 kg", en: "980 kg" },
    loadingMeters: { de: "2,10", en: "2.10" },
    expressNextDay: false,
    b2cNational: true,
  },
];